# Generated by Django 4.2.7 on 2023-11-22 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_slug_profile_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="User",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="Profile",
        ),
    ]
