# Generated by Django 4.2.7 on 2023-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_media",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_media",
            field=models.BooleanField(default=False),
        ),
    ]
