# Generated by Django 4.2.7 on 2023-11-22 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_message_is_media_privatemessage_is_media"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatroom",
            table="ChatRoom",
        ),
        migrations.AlterModelTable(
            name="message",
            table="Message",
        ),
        migrations.AlterModelTable(
            name="privatechatroom",
            table="PrivateChatRoom",
        ),
        migrations.AlterModelTable(
            name="privatemessage",
            table="PrivateMessage",
        ),
    ]
