# Generated by Django 4.2.7 on 2023-11-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "messaging",
            "0007_privateroomfile_messageid_privateroomfile_receiver_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateroomfile",
            name="messageid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.privatemessage",
            ),
        ),
    ]
