# Generated by Django 4.2.7 on 2023-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0008_alter_privateroomfile_messageid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateroomfile",
            name="file",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
