# Generated by Django 4.2.7 on 2023-11-26 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0009_alter_privateroomfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privateroomfile",
            old_name="file",
            new_name="image",
        ),
    ]
