# Generated by Django 4.2.7 on 2023-11-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0010_rename_file_privateroomfile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privateroomfile",
            name="messageid",
        ),
        migrations.AddField(
            model_name="privateroomfile",
            name="message",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.privatemessage",
            ),
            preserve_default=False,
        ),
    ]
