# Generated by Django 4.2.7 on 2023-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0011_remove_privateroomfile_messageid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateroomfile",
            name="image",
            field=models.JSONField(),
        ),
    ]
