# Generated by Django 4.2.7 on 2023-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0013_privateroomfile_processed_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
