# Generated by Django 4.2.7 on 2023-11-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0014_alter_privatemessage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="private_chat_images/"
            ),
        ),
        migrations.DeleteModel(
            name="PrivateRoomFile",
        ),
    ]
