# Generated by Django 4.2.7 on 2023-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0015_privatemessage_image_delete_privateroomfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
    ]
