# Generated by Django 4.2.7 on 2023-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0016_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
