# Generated by Django 4.2.7 on 2023-11-22 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="friendrequest",
            table="FriendRequest",
        ),
    ]
